"""The committed diffs still describe the files they claim to describe.

Two files under `evidence/cluster/` are DeformSplat's, Apache-2.0, and both carry a
local modification. The licence asks that a modified file say so, and neither can:
both are hash-pinned in `evidence/PROVENANCE.toml`, the manifest cites one of the
hashes directly, and `test_conformance.py` and `test_wiring_assertion.py` parse both
by AST out of the source text. A notice inserted into either would break all four at
once — and would stop the copy being what actually ran on the cluster, which is the
only reason it is evidence rather than a dependency.

So the notice sits beside the file: `THIRD_PARTY.md` states the modification, and
`third_party/deformsplat/*.diff` commits the whole thing against the pinned upstream
commit. That is more than the licence asks for, and it turns "the ARAP math, the LBS,
the solver and the optimiser are untouched" from an assurance into thirty lines a
reader can check.

**A committed diff is a transcription, and this project has been bitten by
transcriptions before.** It is written once and then describes a file that can move
underneath it, silently, exactly like a quoted count going stale. Every assertion here
exists to make that impossible: the diff's added lines have to be present in the
deployed file as contiguous blocks, its removed lines have to be gone, its preamble has
to name the hash the record holds, and the line counts `THIRD_PARTY.md` publishes have
to be the line counts the diff actually has.

What this **cannot** check is that the diff is right about *upstream*, because upstream
is not in this repository and deliberately is not — vendoring 1,581 more lines to check
a 30-line claim is the wrong trade. Both diffs were generated by `diff -u` against a
clone at `60955d67d066a8b26e1ed8a92f1c51c902a9ccab` and verified to re-apply cleanly to
it with `patch`. Anyone holding that clone can repeat it; the commit is pinned in three
places so that they can.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pytest

from plan1.provenance import EVIDENCE_ROOT, REPO_ROOT, load_evidence

RECORD = load_evidence()

#: The pinned upstream commit, restated so the diffs are checked against a literal
#: rather than against whatever they happen to say about themselves.
UPSTREAM_COMMIT = "60955d67d066a8b26e1ed8a92f1c51c902a9ccab"
UPSTREAM_REPO = "github.com/vision3d-lab/deformsplat"

DIFF_ROOT = REPO_ROOT / "third_party" / "deformsplat"
THIRD_PARTY = REPO_ROOT / "THIRD_PARTY.md"

#: Each committed diff, and the deployed file it describes.
DIFFS = {
    "helper.py.diff": "cluster/sources_20260729/helper.py",
    "deform_splat.py.diff": "cluster/sources_20260805_patched/deform_splat.py",
}

#: How many lines of this project's own change each diff carries — the number
#: `THIRD_PARTY.md` publishes, declared here so the two cannot drift apart.
#:
#: These are **not** simply the count of `+` lines, and the gap is the point:
#:
#: `helper.py.diff` has 20 added lines and one removed. Nineteen are new content; the
#: twentieth is `return int(covered_count)` reappearing because the upstream file ended
#: without a trailing newline and the deployed one does not. A newline is not an edit.
#:
#: `deform_splat.py.diff` has 12 added lines across two hunks. Eleven are this
#: project's, in one hunk at the `weight` tensor. The twelfth is the second hunk —
#: `{"step": step}` -> `{"step": drag_iterations}` — which is **not** this project's
#: change: `deform_splat.py.prebak`, taken before the patch, already carries it, so it
#: came with the clone. It is in the diff because a diff that hides a real difference
#: is not a diff, and out of this count because attributing it here would claim work
#: that was not done.
AUTHORED_LINES = {"helper.py.diff": 19, "deform_splat.py.diff": 11}


@dataclass(frozen=True)
class Hunk:
    added: tuple[str, ...]
    removed: tuple[str, ...]


@dataclass(frozen=True)
class Diff:
    preamble: tuple[str, ...]
    header: tuple[str, ...]
    hunks: tuple[Hunk, ...]

    @property
    def added(self) -> list[str]:
        return [line for hunk in self.hunks for line in hunk.added]

    @property
    def removed(self) -> list[str]:
        return [line for hunk in self.hunks for line in hunk.removed]

    @property
    def added_runs(self) -> list[tuple[str, ...]]:
        """Consecutive added lines, as the contiguous blocks they must form."""
        runs: list[tuple[str, ...]] = []
        for hunk in self.hunks:
            if hunk.added:
                runs.append(hunk.added)
        return runs


def parse(path: Path) -> Diff:
    """Read one committed diff.

    Leading `#` lines are this repository's prose — `patch` skips them, which is
    checked by the fact that both diffs re-applied cleanly with them present.
    """
    preamble: list[str] = []
    header: list[str] = []
    hunks: list[Hunk] = []
    added: list[str] = []
    removed: list[str] = []
    in_body = False

    for line in path.read_text().splitlines():
        if not in_body:
            if line.startswith("---"):
                in_body = True
                header.append(line)
            else:
                preamble.append(line)
            continue
        if line.startswith("+++") or line.startswith("---"):
            header.append(line)
        elif line.startswith("@@"):
            if added or removed:
                hunks.append(Hunk(tuple(added), tuple(removed)))
                added, removed = [], []
        elif line.startswith("+"):
            added.append(line[1:])
        elif line.startswith("-"):
            removed.append(line[1:])
        # a bare "\" line is diff's no-newline-at-EOF marker, not content; a leading
        # space is unchanged context. Neither is part of the change.
    if added or removed:
        hunks.append(Hunk(tuple(added), tuple(removed)))
    return Diff(tuple(preamble), tuple(header), tuple(hunks))


def deployed_lines(name: str) -> list[str]:
    return RECORD.resolve(DIFFS[name]).read_text().splitlines()


def contains_run(haystack: list[str], run: tuple[str, ...]) -> bool:
    width = len(run)
    return any(
        tuple(haystack[i : i + width]) == run for i in range(len(haystack) - width + 1)
    )


# ── the diff describes the file that is actually here ───────────────────────
@pytest.mark.parametrize("name", sorted(DIFFS))
def test_every_added_block_is_present_in_the_deployed_file_contiguously(name):
    """Line-by-line membership is too weak — it passes on a file that contains the
    same lines scattered anywhere. The change was a block; it has to still be one."""
    lines = deployed_lines(name)
    for run in parse(DIFF_ROOT / name).added_runs:
        assert contains_run(lines, run), (
            f"{name}: this block is in the diff but not contiguous in "
            f"{DIFFS[name]}:\n" + "\n".join(run)
        )


@pytest.mark.parametrize("name", sorted(DIFFS))
def test_no_removed_line_survives_in_the_deployed_file(name):
    """The other direction, and it is weaker than it looks on one of the two.

    `helper.py.diff` removes exactly one line and adds it straight back — the file
    gained a trailing newline. That line is *supposed* to still be there, so it is
    excluded and the check is vacuous for that diff. It is not vacuous for
    `deform_splat.py.diff`, where the removed `{"step": step}` really must be gone,
    and leaving the assertion parametrised over both is what makes it keep working if
    a future edit removes something real from either.
    """
    diff = parse(DIFF_ROOT / name)
    genuinely_removed = set(diff.removed) - set(diff.added)
    survivors = sorted(genuinely_removed.intersection(deployed_lines(name)))
    assert not survivors, f"{name}: removed by the diff, still in the file: {survivors}"


# ── the diff names what it is a diff against ────────────────────────────────
@pytest.mark.parametrize("name", sorted(DIFFS))
def test_the_diff_names_the_pinned_upstream_commit_and_repository(name):
    text = (DIFF_ROOT / name).read_text()
    assert UPSTREAM_COMMIT in text, name
    assert UPSTREAM_REPO in text, name
    assert "Apache-2.0" in text, name


@pytest.mark.parametrize("name", sorted(DIFFS))
def test_the_diff_names_the_hash_the_record_holds_for_that_file(name):
    """Binds the diff to the provenance row rather than to a path.

    A path can be repointed at a different file and every other assertion here would
    still pass against the new one. The hash cannot.
    """
    entry = next(e for e in RECORD.files if e.path == DIFFS[name])
    assert entry.sha256 in (DIFF_ROOT / name).read_text(), (
        f"{name} does not name {entry.sha256}, the recorded hash of {entry.path}"
    )


@pytest.mark.parametrize("name", sorted(DIFFS))
def test_the_diff_header_points_at_the_deployed_path(name):
    header = "\n".join(parse(DIFF_ROOT / name).header)
    assert f"evidence/{DIFFS[name]}" in header, header


# ── the published counts are the counts ─────────────────────────────────────
@pytest.mark.parametrize("name", sorted(AUTHORED_LINES))
def test_the_published_line_count_is_what_the_diff_actually_contains(name):
    """`THIRD_PARTY.md` publishes "+19" and "+11"; `PROVENANCE.toml` repeats them.

    A count quoted into two documents is a count that goes stale in at least one, so
    it is read back out of the diff here. See `AUTHORED_LINES` for why the number is
    not simply `len(added)` on either file.
    """
    diff = parse(DIFF_ROOT / name)
    newline_only = set(diff.added).intersection(diff.removed)
    drift = [h for h in diff.hunks if h.removed and set(h.removed) - newline_only]
    authored = sum(
        len([line for line in hunk.added if line not in newline_only])
        for hunk in diff.hunks
        if hunk not in drift
    )
    assert authored == AUTHORED_LINES[name]


def test_third_party_md_publishes_those_counts_and_their_sum():
    text = THIRD_PARTY.read_text()
    total = sum(AUTHORED_LINES.values())
    assert total == 30
    for count in AUTHORED_LINES.values():
        assert f"+{count} lines" in text, count
    assert f"{total} lines in total" in text


def test_the_clone_drift_is_disclosed_rather_than_quietly_excluded():
    """The one line left out of the count has to be findable by a reader.

    Excluding it from "this project's change" is correct and is also the shape of a
    convenient omission, so the disclosure is asserted in all three places a reader
    might land: the diff, the licence file, and the provenance row.
    """
    for text in (
        (DIFF_ROOT / "deform_splat.py.diff").read_text(),
        THIRD_PARTY.read_text(),
        next(
            e for e in RECORD.files if e.path == DIFFS["deform_splat.py.diff"]
        ).modification
        or "",
    ):
        assert "prebak" in text
        assert "drag_iterations" in text


# ── the notices are beside the files, not inside them ───────────────────────
@pytest.mark.parametrize("name", sorted(DIFFS))
def test_the_third_party_rows_carry_all_four_upstream_fields(name):
    entry = next(e for e in RECORD.files if e.path == DIFFS[name])
    assert entry.upstream_repo == UPSTREAM_REPO
    assert entry.upstream_commit == UPSTREAM_COMMIT
    assert entry.upstream_licence and "Apache-2.0" in entry.upstream_licence
    assert entry.modification and "MODIFIED" in entry.modification


def test_only_the_two_deformsplat_sources_claim_an_upstream():
    """Third-party status is a property of two files, and saying so is what stops
    the fields becoming decoration sprayed across rows that are this project's own."""
    claimed = {e.path for e in RECORD.files if e.upstream_repo is not None}
    assert claimed == set(DIFFS.values())


def test_nothing_authored_here_was_written_into_the_evidence_directory():
    """Trap the whole placement decision turns on.

    `evidence/` is copies, pinned by hash and asserted in both directions; a `LICENSE`
    or a `.diff` written into it would need a provenance row saying it came from an
    archive it never came from. Authored files live outside, so the invariant that
    every file under `evidence/` is a copy of something survives attribution.
    """
    for authored in (THIRD_PARTY, REPO_ROOT / "LICENSE", DIFF_ROOT):
        assert not authored.resolve().is_relative_to(EVIDENCE_ROOT), authored


def test_none_of_the_attribution_files_are_gitignored():
    """This repository has already shipped this bug once.

    A blanket `*.png` rule silently matched six tracked figures; they survived only
    because git keeps tracking what it already tracks, so every test passed and
    `git status` was clean while the *rule* said they should not be there.
    `test_suite_shape.py` closed that for the evidence base and the port. These files
    are in neither, so they need saying separately — and an attribution file that a
    fresh `git add` drops is worse than no attribution file, because the repository
    then looks compliant to everyone holding a clone made from history.
    """
    import subprocess

    paths = [
        "LICENSE",
        "THIRD_PARTY.md",
        "third_party/deformsplat/LICENSE",
        *(f"third_party/deformsplat/{name}" for name in sorted(DIFFS)),
    ]
    for path in paths:
        assert (REPO_ROOT / path).is_file(), path

    # `--no-index` for the same reason it is load-bearing in test_suite_shape.py:
    # without it, `check-ignore` reports nothing for an already-tracked file, which
    # is precisely the blind spot that let the `*.png` rule sit unnoticed.
    result = subprocess.run(
        ["git", "check-ignore", "--no-index", "--stdin"],
        input="\n".join(paths),
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    assert result.returncode == 1, (
        f"attribution files matched by .gitignore, so a fresh `git add` would drop "
        f"them:\n{result.stdout}"
    )


def test_the_apache_licence_text_travels_with_the_code_it_covers():
    """Apache-2.0 §4(a): recipients of the work get a copy of the licence. 1,581
    lines of it are redistributed here, so the text is committed rather than linked."""
    text = (DIFF_ROOT / "LICENSE").read_text()
    assert "Apache License" in text
    assert "Version 2.0, January 2004" in text
    assert "TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION" in text


def test_this_repository_declares_its_own_licence_and_scopes_it():
    """A repository that ships third-party code and has no LICENSE of its own leaves
    a reader unable to tell which terms apply to what. Both halves are asserted: that
    there is one, and that it says what it does not cover."""
    text = (REPO_ROOT / "LICENSE").read_text()
    assert "MIT License" in text
    assert "THIRD_PARTY.md" in text
    assert "evidence/cluster/" in text
