#!/usr/bin/env bash
#
# verify.sh — the green gate. One command, four claims.
#
#     ./scripts/verify.sh
#
# It installs the repository, runs the whole suite, regenerates the published
# comparison table, and diffs the regenerated table against the committed one.
# Anything less than all four is not the claim being made: a green suite that
# never rebuilt the table says nothing about whether the table is reproducible,
# and a table that rebuilds without the suite says nothing about whether the
# numbers in it were assembled under the rules.
#
# It is meant to be run the way an examiner meets it — a fresh clone at a path
# with no sibling working trees, in a clean environment, with nothing
# pre-installed:
#
#     git clone <url> plan1-comparison && cd plan1-comparison
#     python3 -m venv .venv && . .venv/bin/activate
#     ./scripts/verify.sh
#
# The suite ERRORS rather than shrinks if an input or a dependency is missing, so
# a green run here cannot be a smaller green run in disguise. That is the failure
# this repository was built to close: it once reported `60 passed, 20 skipped`,
# exit code 0, with the wiring gate among the 80 that never ran.

set -euo pipefail

cd "$(dirname "$0")/.."

echo "== 1/4  install =============================================="
python -m pip install -e ".[test]" --quiet
python -m pip show plan1-comparison | sed -n '1,2p'

echo
echo "== 2/4  the whole suite ======================================"
# -p no:randomly and no filters: the total that prints here is the total that
# exists. tests/test_suite_shape.py asserts it, so a suite that quietly shrank
# fails rather than reporting a smaller green number.
python -m pytest

echo
echo "== 3/4  regenerate the published table ======================="
python scripts/build_table.py -o out/comparison_table.md

echo
echo "== 4/4  diff it against the committed copy ==================="
if git diff --exit-code -- out/comparison_table.md; then
    echo "clean — the table regenerated byte-identically."
else
    echo "REGENERATED TABLE DIFFERS FROM THE COMMITTED ONE (above)." >&2
    exit 1
fi

echo
echo "=============================================================="
echo "VERIFIED — installed, suite green, table regenerates identically."
