#!/usr/bin/env bash
#
# verify.sh — the green gate. One command, five claims.
#
#     ./scripts/verify.sh
#
# It installs the repository, runs the whole suite, regenerates both published
# comparison tables, diffs the regenerated tables against the committed ones, and
# rebuilds the §6.4 figure to check its data record still regenerates.
# Anything less than all five is not the claim being made: a green suite that
# never rebuilt the tables says nothing about whether they are reproducible,
# and a table that rebuilds without the suite says nothing about whether the
# numbers in it were assembled under the rules.
#
# It is meant to be run the way an examiner meets it — a fresh clone at a path
# with no sibling working trees, in a clean environment, with nothing
# pre-installed:
#
#     git clone <url> plan1-comparison && cd plan1-comparison
#     python3 -m venv .venv && . .venv/bin/activate
#     ./scripts/verify.sh
#
# The suite ERRORS rather than shrinks if an input or a dependency is missing, so
# a green run here cannot be a smaller green run in disguise. That is the failure
# this repository was built to close: it once reported `60 passed, 20 skipped`,
# exit code 0, with the wiring gate among the 80 that never ran.

set -euo pipefail

cd "$(dirname "$0")/.."

echo "== 1/5  install =============================================="
python -m pip install -e ".[test]" --quiet
python -m pip show plan1-comparison | sed -n '1,2p'

echo
echo "== 2/5  the whole suite ======================================"
# -p no:randomly and no filters: the total that prints here is the total that
# exists. tests/test_suite_shape.py asserts it, so a suite that quietly shrank
# fails rather than reporting a smaller green number.
python -m pytest

echo
echo "== 3/5  regenerate the published tables ======================"
# Both assets. Two manifests, two tables, one assembler — and the penguin's is
# rebuilt here on every run precisely so that work on the second asset cannot move
# the first without saying so. That is not hypothetical: the trex table needed the
# byline's pre-registration and the caption's limitations to become manifest-declared
# rather than renderer-fixed, and both changes ran through the penguin's code path.
python scripts/build_table.py manifests/penguin_deformsplat.toml -o out/comparison_table.md
python scripts/build_table.py manifests/trex_deformsplat.toml -o out/trex_comparison_table.md

echo
echo "== 4/5  diff them against the committed copies ==============="
if git diff --exit-code -- out/comparison_table.md out/trex_comparison_table.md; then
    echo "clean — both tables regenerated byte-identically."
else
    echo "A REGENERATED TABLE DIFFERS FROM THE COMMITTED ONE (above)." >&2
    exit 1
fi

echo
echo "== 5/5  rebuild the figure and diff its data record =========="
# Written to a scratch directory rather than over `out/`, deliberately. The figure's
# DATA record regenerates byte-identically and is diffed here; the PNG does not and
# is not, because a matplotlib PNG's bytes depend on the matplotlib version, on
# freetype and on platform font rasterisation. Rebuilding in place would leave an
# examiner with a dirty working tree for having a different matplotlib, which says
# nothing about whether anything is wrong. What is checked is what can be: the
# numbers behind the picture, and that the picture draws from them at all —
# `render()` recomputes each panel's hash and refuses to draw on a mismatch.
FIGURE_TMP="$(mktemp -d)"
trap 'rm -rf "$FIGURE_TMP"' EXIT
python scripts/make_projection_figure.py \
    --json "$FIGURE_TMP/fig.json" --png "$FIGURE_TMP/fig.png" >/dev/null
if diff -u out/fig_64_penguin_projection.json "$FIGURE_TMP/fig.json"; then
    echo "clean — the figure's data record regenerated byte-identically."
else
    echo "REGENERATED FIGURE RECORD DIFFERS FROM THE COMMITTED ONE (above)." >&2
    exit 1
fi

echo
echo "=============================================================="
echo "VERIFIED — installed, suite green, table and figure regenerate identically."
